services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - WDS_SOCKET_HOST=localhost
    depends_on:
      - backend

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    dns:
      - 1.1.1.1
      - 8.8.8.8
    environment:
      
      - DATABASE_URL=postgresql://postgres:Aasal22!!@projectswtm.c9gqueuwynyt.eu-north-1.rds.amazonaws.com:5432/fahrzeugservice
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - LANGSMITH_API_KEY=${LANGSMITH_API_KEY}
      - TAVILY_API_KEY=${TAVILY_API_KEY}
      - LANGSMITH_PROJECT=${LANGSMITH_PROJECT}
      - LANGSMITH_TRACING_V2=${LANGSMITH_TRACING_V2}
      - DATABASE_HOST=projectswtm.c9gqueuwynyt.eu-north-1.rds.amazonaws.com
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=Aasal22!!
      - DATABASE_NAME=fahrzeugservice
      - DATABASE_SCHEMA=postgresql+psycopg
      - DATABASE_SSLMODE=require
      - EMBEDDING_COLLECTION_NAME=documents
      - DOCUMENTS_PATH=/app/uploads
      - SERPAPI_KEY=${SERPAPI_KEY}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - SMTP_TO=${SMTP_TO}
    volumes:
      - ./backend:/app
   

  keycloak:
    image: quay.io/keycloak/keycloak:26.4.2
    dns:
      - 1.1.1.1
      - 8.8.8.8
    environment:
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://projectswtm.c9gqueuwynyt.eu-north-1.rds.amazonaws.com:5432/keycloak
      - KC_DB_USERNAME=postgres
      - KC_DB_PASSWORD=Aasal22!!
      - KC_TRANSACTION_XA_TIMEOUT=1800
    ports:
      - "8080:8080"
    command: ["start-dev", "--import-realm"]
   
    volumes:
      - keycloak_data:/opt/keycloak/data
      - ./keycloak/realm.json:/opt/keycloak/data/import/realm.json

volumes:
 
  keycloak_data: