"""Initial migration clean

Revision ID: f66cbca9a605
Revises: 
Create Date: 2026-01-13 16:29:20.264962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f66cbca9a605'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_DamageEvents_DamageEvent_id'), table_name='DamageEvents')
    op.drop_index(op.f('ix_DamageEvents_customer_id'), table_name='DamageEvents')
    op.drop_index(op.f('ix_DamageEvents_id'), table_name='DamageEvents')
    op.drop_table('DamageEvents')
    op.drop_index(op.f('ix_chat_messages_user_conv'), table_name='chat_messages')
    op.create_index(op.f('ix_chat_messages_conversation_id'), 'chat_messages', ['conversation_id'], unique=False)
    op.drop_column('damage_event', 'estimated_damage')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('damage_event', sa.Column('estimated_damage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_chat_messages_conversation_id'), table_name='chat_messages')
    op.create_index(op.f('ix_chat_messages_user_conv'), 'chat_messages', ['user_id', 'conversation_id'], unique=False)
    op.create_table('DamageEvents',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('damage_event_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('damage_type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('damage_date', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('damage_location', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('vehicle', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('police_involved', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('third_party_involved', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('estimated_damage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('DamageEvents_pkey'))
    )
    op.create_index(op.f('ix_DamageEvents_id'), 'DamageEvents', ['id'], unique=False)
    op.create_index(op.f('ix_DamageEvents_customer_id'), 'DamageEvents', ['customer_id'], unique=False)
    op.create_index(op.f('ix_DamageEvents_DamageEvent_id'), 'DamageEvents', ['damage_event_id'], unique=True)
    # ### end Alembic commands ###
